//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WingAir_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aviones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aviones()
        {
            this.Vuelos = new HashSet<Vuelos>();
        }
    
        public int AvionId { get; set; }
        public int TipoId { get; set; }
        public string Codigo { get; set; }
        public double HorasVuelo { get; set; }
        public int CapacidadPasajeros { get; set; }
    
        public virtual TiposAviones TiposAviones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vuelos> Vuelos { get; set; }
    }
}
