//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WingAir_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WingAirEntities : DbContext
    {
        public WingAirEntities()
            : base("name=WingAirEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aeropuertos> Aeropuertos { get; set; }
        public virtual DbSet<Aviones> Aviones { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<Pilotos> Pilotos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TiposAviones> TiposAviones { get; set; }
        public virtual DbSet<Vuelos> Vuelos { get; set; }
    }
}
