//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WingAir_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        public int VueloId { get; set; }
        public int AeropuertoOrigenId { get; set; }
        public int AeropuertoDestinoId { get; set; }
        public int AvionId { get; set; }
        public int PilotoId { get; set; }
        public int EstatusId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public System.DateTime FechaLlegadaEstimada { get; set; }
        public System.DateTime FechaLlegadaReal { get; set; }
        public double HorasVuelo { get; set; }
    
        public virtual Aeropuertos Aeropuertos { get; set; }
        public virtual Aeropuertos Aeropuertos1 { get; set; }
        public virtual Aviones Aviones { get; set; }
        public virtual Estatus Estatus { get; set; }
        public virtual Pilotos Pilotos { get; set; }
    }
}
